from django.urls import path 
from YOYO_APP.views import *

urlpatterns = [
   path('',login_yoyo,name='login'),
   path('register/',register_yoyo,name='register'),
   path('home/',home_yoyo,name='home'),
   path('Brainstormer/',brain_yoyo,name='brain_yoyo'),
   path('Career_guide/',Career_guide_yoyo,name='Career_guide_yoyo'),
   path('Chess_champ/',Chess_champ_yoyo,name='Chess_champ_yoyo'),
   path('Coding_partner/',Coding_partner_yoyo,name='Coding_partner_yoyo'),
   path('ForgotPassword/',ForgotPassword_yoyo,name='ForgotPassword_yoyo'),
   path('Learning_coach/',Learning_coach_yoyo,name='Learning_coach_yoyo'),
   path('NewGem/',NewGem_yoyo,name='NewGem_yoyo'),
   path('Public_Links/',Public_Links_yoyo,name='Public_Links_yoyo'),
   path('SavedInfo/',SavedInfo_yoyo,name='SavedInfo_yoyo'),
   path('save-info/',save_info,name='save_info'),
   path('update-saved-info/<int:info_id>/',update_saved_info,name='update_saved_info'),
   path('delete-saved-info/<int:info_id>/',delete_saved_info,name='delete_saved_info'),
   path('delete-all-saved-info/',delete_all_saved_info,name='delete_all_saved_info'),
   path('Search/',Search_yoyo,name='Search_yoyo'),
   path('Upgrad/',Upgrad_yoyo,name='Upgrad_yoyo'),
   path('Writing_editor/',Writing_editor_yoyo,name='Writing_editor_yoyo'),
   path('Explore_Gem/',Explore_Gem_yoyo,name='Explore_Gem_yoyo'),
   path('logout/',logout_yoyo,name='logout_yoyo'), 
   path("chat/new/", new_chat, name="new_chat"),
   path("chat/", chat_detail, name="chat_detail"),   
   path("chat/<int:chat_id>/", chat_detail, name="chat_detail"),
   path("chat/<int:chat_id>/send/", send_message, name="send_message"),
   path("chat/0/send/", send_message, name="send_message_new"),
   path("chat/<int:chat_id>/rename/", rename_chat, name="rename_chat"),
   path("chat/<int:chat_id>/delete/", delete_chat, name="delete_chat"),
   path("gem/<int:gem_id>/", gem_detail, name="gem_detail"),
   path("newgem/preview-chat/", newgem_preview_chat, name="newgem_preview_chat"),
   path("gem/<int:gem_id>/rename/", rename_gem, name="rename_gem"),
   path("gem/<int:gem_id>/delete/", delete_gem, name="delete_gem"),
   path("chat/<int:gem_id>/", chat_page, name="chat_page"),
   path("copy_gem/<int:gem_id>/", copy_gem, name="copy_gem"),
   path("reset-password/<uidb64>/<token>/", ResetPassword_yoyo, name="reset_password"),
   path("switch-account/<int:account_id>/", switch_account, name="switch_account"),


]
