# Generated by Django 5.2.5 on 2025-08-27 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YOYO_APP', '0002_chatmessages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessages',
        ),
    ]
