# Generated by Django 5.2.5 on 2025-08-28 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YOYO_APP', '0004_chatmessages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessages',
        ),
    ]
