# Generated by Django 5.2.5 on 2025-09-03 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YOYO_APP', '0007_gem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gem',
        ),
    ]
