# Generated by Django 5.2.5 on 2025-09-04 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YOYO_APP', '0009_gem'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='gem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='YOYO_APP.gem'),
        ),
    ]
