# Generated by Django 5.2.5 on 2025-09-13 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YOYO_APP', '0014_userdata_is_active_userdata_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_infos', to='YOYO_APP.userdata')),
            ],
        ),
    ]
